name: Docker Build on Commit

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '**.py'
      - 'requirements.txt'

env:
  IMAGE_NAME: stash-folder-view

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 获取短 SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
            ${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ env.GIT_SHA }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
          cache-to: type=inline
